/* ============================================================
 * app-state.js — 应用共享状态
 * 拆分自原 app.js：集中管理 DOM 引用与可变状态，
 * 供 app-tools / app-library / app-settings / app-reader / app.js 使用
 * ============================================================ */
(function (global) {
  'use strict';

  const $ = (id) => document.getElementById(id);
  global.$ = $; // 供各拆分模块使用（如 init 里的 $('btn-xxx')）

  /** 全部 DOM 元素引用 */
  global.AppEls = {
    topbar: $('topbar'),
    readerWrap: $('reader-wrap'),
    readerEl: $('reader'),
    bookTitle: $('book-title'),
    bookAuthor: $('book-author'),
    progressText: $('progress-text'),
    libraryView: $('library-view'),
    bookGrid: $('book-grid'),
    emptyHint: $('empty-hint'),
    fileInput: $('file-input'),
    fabMain: $('fab-main'),
    fabActions: $('fab-actions'),
    fabNewFolder: $('fab-new-folder'),
    fabImport: $('fab-import'),
    btnBack: $('btn-back'),
    btnPrev: $('btn-prev'),
    btnNext: $('btn-next'),
    panelToc: $('panel-toc'),
    tocList: $('toc-list'),
    panelBookmarks: $('panel-bookmarks'),
    bookmarkList: $('bookmark-list'),
    btnAddBookmark: $('btn-add-bookmark'),
    searchPanel: $('search-panel'),
    searchInput: $('search-input'),
    searchResults: $('search-results'),
    settingsPanel: $('settings-panel'),
    customBgInput: $('custom-bg-input'),
    customTextInput: $('custom-text-input'),
    customAccentInput: $('custom-accent-input'),
    customBorderInput: $('custom-border-input'),
    customTextDimInput: $('custom-textdim-input'),
    btnBgReset: $('btn-bg-reset'),
    btnTextReset: $('btn-text-reset'),
    btnAccentReset: $('btn-accent-reset'),
    btnBorderReset: $('btn-border-reset'),
    btnTextDimReset: $('btn-textdim-reset'),
    customColorsToggle: $('custom-colors-toggle'),
    customColorsBody: $('custom-colors-body'),
    customColorsSection: $('custom-colors-section'),
    fontSizeRange: $('font-size-range'),
    fontSizeVal: $('font-size-val'),
    lineHeightRange: $('line-height-range'),
    lineHeightVal: $('line-height-val'),
    marginRange: $('margin-range'),
    marginVal: $('margin-val'),
    fontPicker: $('font-picker'),
    fontPickerBtn: $('font-picker-btn'),
    fontPickerLabel: $('font-picker-label'),
    fontPickerMenu: $('font-picker-menu'),
    flowSeg: $('flow-seg'),
    themePicker: $('theme-picker'),
    themePickerBtn: $('theme-picker-btn'),
    themePickerLabel: $('theme-picker-label'),
    themePickerMenu: $('theme-picker-menu'),
    volumeKeyToggle: $('volume-key-toggle'),
    dropOverlay: $('drop-overlay'),
    toast: $('toast'),
    folderBar: $('folder-bar'),
    folderNav: $('folder-nav'),
    folderName: $('folder-name'),
    fabWrap: $('fab-wrap'),
    btnFolderBack: $('btn-folder-back'),
    btnFolderImport: $('btn-folder-import'),
    btnFolderRename: $('btn-folder-rename'),
    btnFolderDelete: $('btn-folder-delete'),
    moveModal: $('move-modal'),
    moveList: $('move-list'),
    btnMoveClose: $('btn-move-close'),
    inputModal: $('input-modal'),
    inputModalTitle: $('input-modal-title'),
    inputField: $('input-modal-field'),
    btnInputOk: $('btn-input-ok'),
    btnInputCancel: $('btn-input-cancel'),
    btnInputClose: $('btn-input-close'),
    confirmModal: $('confirm-modal'),
    confirmText: $('confirm-modal-text'),
    btnConfirmOk: $('btn-confirm-ok'),
    btnConfirmCancel: $('btn-confirm-cancel'),
    cardMenu: $('card-menu'),
    cardMenuTitle: $('card-menu-title'),
    cardMenuMove: $('card-menu-move'),
    cardMenuDelete: $('card-menu-delete'),
    cardMenuCancel: $('card-menu-cancel'),
    cardMenuInfo: $('card-menu-info'),
    cardMenuSelect: $('card-menu-select'),
    btnSort: $('btn-sort'),
    btnLibrarySettings: $('btn-library-settings'),
    librarySearch: $('library-search'),
    sortMenu: $('sort-menu'),
    sortMenuCancel: $('sort-menu-cancel'),
    btnImportFont: $('btn-import-font'),
    fontFileInput: $('font-file-input'),
    customFontList: $('custom-font-list'),
    selectBar: $('select-bar'),
    selectCount: $('select-count'),
    selectMove: $('select-move'),
    selectDelete: $('select-delete'),
    selectAll: $('select-all'),
    selectCancel: $('select-cancel'),
    bookInfoModal: $('book-info-modal'),
    btnInfoClose: $('btn-info-close'),
    btnInfoClose2: $('btn-info-close2'),
    btnInfoRead: $('btn-info-read'),
    bookInfoCover: $('book-info-cover'),
    biTitle: $('bi-title'),
    biAuthor: $('bi-author'),
    biType: $('bi-type'),
    biSize: $('bi-size'),
    biProgress: $('bi-progress'),
    biAdded: $('bi-added'),
    biLastread: $('bi-lastread'),
    hlBar: $('hl-bar'),
    hlCancel: $('hl-cancel'),
    hlClear: $('hl-clear'),
    hlColorInput: $('hl-color-input'),
    readerStatus: $('reader-status'),
    statusTime: $('status-time'),
    statusBatteryFill: $('battery-fill'),
    statusBatteryText: $('battery-text'),
    btnExportBackup: $('btn-export-backup'),
    btnImportBackup: $('btn-import-backup'),
    btnExportNotes: $('btn-export-notes'),
    backupFileInput: $('backup-file-input'),
    settingsMask: $('settings-mask'),
    langSeg: $('lang-seg'),
  };

  /** 可变应用状态（拆分前为 IIFE 闭包变量） */
  global.AppState = {
    inputResolve: null,   // 输入弹窗 promise resolve
    confirmResolve: null, // 确认弹窗 promise resolve
    reader: null,         // 当前 Reader 实例
    currentBookId: null,
    currentToc: [],
    toastTimer: null,
    lastProgressSave: 0,
    cardMenuBookId: null,
    bookInfoId: null,
    pendingHighlight: null, // 选中文本待划线 { cfi, text }
    fontBlobUrls: {},       // 自定义字体 id → blob URL
    coverUrls: new Map(),   // 书籍 id → 封面 blob URL
    statusTimer: null,
    currentFolderId: null,  // null = 书库主页
    librarySearch: '',      // 书库搜索词
    moveBookIds: null,      // 移动弹窗目标
    selectMode: false,
    selectedIds: new Set(),
    autoHideTimer: null,
  };
})(window);
